### ISSUE TITLE
Document health check buildpack usage on Paketo web site

### ISSUE THREAD

**Issue by dmikusa** [paketo-buildpacks/health-checker#125]
## Describe the Enhancement

There is no documentation on paketo.io/docs for using the Health Checker buildpack. Add documentation for usage with pack, Spring Boot build tools, `docker run` and Docker Compose.

## Motivation

It helps to know how to use the buildpack 😀

**Comment by detomarco** [comment]
any update on this? 

I'm trying to use healtcheck in a spring boot app but I didn't find any official resource that describe how to do it.

This is my gradle configuration 
```kotlin
buildpacks = listOf(
    "gcr.io/paketo-buildpacks/java:latest",
    "gcr.io/paketo-buildpacks/health-checker:latest",
)
environment = mapOf(
    "BP_HEALTH_CHECKER_ENABLED" to "true"
)
```
Docker compose
```yaml
healthcheck:
    test: [ "CMD", "/cnb/process/health-check" ]
    interval: 3s
    retries: 10
    start_period: 10s
    timeout: 180s
```

but then I get this error in the healtcheck logs of my container

```json

{
   "Start": "2024-10-25T19:50:37.999496253Z",
   "End": "2024-10-25T19:50:38.06885967Z",
   "ExitCode": -1,
   "Output": "OCI runtime exec failed: exec failed: unable to start container process: exec: \"/cnb/process/health-check\": stat /cnb/process/health-check: no such file or directory: unknown"
},

```

There is really no documentation on how to do it properly
